### ISSUE TITLE
experiments

### ISSUE THREAD

**Issue by XuanWangVC** [facebookresearch/mvp#2]
Hi! What awesome work! When will you share the data and experiments configs?

Best wishes!

**Comment by yeong5366** [comment]
https://github.com/facebookresearch/mvp/releases/tag/v0.1
You can find it here!

**Comment by stephenlombardi** [comment]
Thanks! The data release is still being put together and unfortunately I don't have a firm date on when it will be done. I hope it will be within the next month or two. I will try to move the process along.

**Comment by XuanWangVC** [comment]
Thank you very much!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/02/22,
15:32:46

Yeong-Hyeon Kim ***@***.***> 于2022年2月4日周五 15:24写道：

**Comment by XuanWangVC** [comment]
Hello! When I use the provided data, I find the file  KRT2_0.5x is lost.
Should we obtain it by exploiting some scripts to tackle the camera
parameters?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/02/22,
17:32:18

Yeong-Hyeon Kim ***@***.***> 于2022年2月4日周五 15:24写道：

**Comment by stephenlombardi** [comment]
Hi Yeong-Hyeon,
Currently the KRT file is held up with the rest of the dataset release. I could provide it but it wouldn't be much help by itself because to render or otherwise evaluate the pretrained model, you'd need the per-frame vertex positions and texture maps that are input to the encoder to evaluate the decoder and render the model. If you're just looking for the correct format of the file to test with your own data, you can check out the file experiments/dryice1/KRT for an example.
-- Steve

**Comment by XuanWangVC** [comment]
Thank you for your reply.  It's helpful!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/02/22,
10:54:55

Stephen Lombardi ***@***.***> 于2022年2月10日周四 04:57写道：
